basePath: /v2
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Job:
    properties:
      config:
        type: string
      createdAt:
        type: string
      creator:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      errorCode:
        type: integer
      id:
        type: integer
      label:
        items:
          type: string
        type: array
      result:
        $ref: '#/definitions/model.JobResult'
      status:
        $ref: '#/definitions/model.Status'
      tasks:
        items:
          $ref: '#/definitions/model.Task'
        type: array
      title:
        type: string
      updatedAt:
        type: string
    type: object
  model.JobResult:
    properties:
      artifacts:
        description: 输出产物路径
        items:
          type: string
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      jobID:
        description: Foreign key for Job
        type: integer
      logs:
        description: 执行日志
        type: string
      metrics:
        description: 结构化指标数据
        type: string
      output:
        description: 主要输出结果
        type: string
      updatedAt:
        type: string
    type: object
  model.Status:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Pending
    - Started
    - Running
    - Failure
    - Success
  model.Task:
    description: task table
    properties:
      config:
        type: string
      createdAt:
        type: string
      creator:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      errorCode:
        type: integer
      id:
        type: integer
      jobID:
        type: integer
      label:
        description: 修改为字符串切片并使用JSON类型存储
        items:
          type: string
        type: array
      status:
        $ref: '#/definitions/model.Status'
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: BSD 3-Clause License
    url: https://opensource.org/license/bsd-3-clause
  termsOfService: http://swagger.io/terms/
  title: aha_webserver API
  version: "1.0"
paths:
  /job:
    post:
      consumes:
      - application/json
      parameters:
      - description: 信息
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/model.Job'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Job'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: 创建新Job
      tags:
      - Job管理
  /job/{id}:
    get:
      parameters:
      - description: JobID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Job'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: 获取任务详情
      tags:
      - Job管理
  /task:
    post:
      consumes:
      - application/json
      parameters:
      - description: 任务信息
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: 创建新任务
      tags:
      - 任务管理
  /task/{id}:
    get:
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: 获取任务详情
      tags:
      - 任务管理
swagger: "2.0"
